[/Script/Engine.InputSettings]
+AxisConfig=(AxisKeyName="MoveForward",AxisProperties=(DeadZone=0.2,Sensitivity=1.f))
+AxisConfig=(AxisKeyName="MoveRight",AxisProperties=(DeadZone=0.2,Sensitivity=1.f))
+ActionConfig=(ActionKeyName="Jump")
+ActionConfig=(ActionKeyName="LightAttack")
+ActionConfig=(ActionKeyName="HeavyAttack")
+ActionConfig=(ActionKeyName="Special")
+ActionConfig=(ActionKeyName="Dodge")
+ActionConfig=(ActionKeyName="LockOn")
+ActionConfig=(ActionKeyName="SwitchLockOn")

bEnableLegacyInputScales=True
DefaultPlayerInputClass=/Script/Engine.PlayerInput
DefaultInputComponentClass=/Script/Engine.InputComponent

; WASD 移动
+AxisMappings=(Axis="MoveForward",Key=W,Scale=1.0)
+AxisMappings=(Axis="MoveForward",Key=S,Scale=-1.0)
+AxisMappings=(Axis="MoveForward",Key=Up,Scale=1.0)
+AxisMappings=(Axis="MoveForward",Key=Down,Scale=-1.0)
+AxisMappings=(Axis="MoveRight",Key=A,Scale=-1.0)
+AxisMappings=(Axis="MoveRight",Key=D,Scale=1.0)

; 动作按键
+ActionMappings=(Action="Jump",Key=SpaceBar,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="LightAttack",Key=LeftMouseButton,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="HeavyAttack",Key=RightMouseButton,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="Dodge",Key=LeftShift,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="LockOn",Key=Q,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="SwitchLockOn",Key=E,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
+ActionMappings=(Action="Special",Key=R,bShift=False,bCtrl=False,bAlt=False,bCmd=False)
