#!/usr/bin/env python3
"""
Sprite Asset Importer for UE5 — 格斗萌主

Copies AI-generated sprite frames from design/assets/output/ to UE5 Content/ directory
in the correct folder structure for AnimatedSprite2D / Texture2D assets.

Usage:
    python3 import_sprites_to_ue5.py [--dry-run] [--ue-content-path PATH]

The script:
1. Scans design/assets/output/{character}/ for PNG frames
2. Copies them to UE5 Content/Characters/{Character}/{Animation}/ structure
3. Generates a manifest of imported assets
4. (Optional) Generates Python import commands for UE5 Python API
"""

import argparse
import os
import re
import shutil
import sys
from pathlib import Path

# Project root (parent of src_ue5/)
PROJECT_ROOT = Path(__file__).parent.parent  # tools/ -> first-game/
OUTPUT_DIR = PROJECT_ROOT / "design" / "assets" / "output"

# Default UE5 Content path (relative to project)
DEFAULT_CONTENT_PATH = PROJECT_ROOT / "src_ue5" / "Content"

# Animation types to import
ANIMATION_TYPES = [
    "idle", "walk", "run",
    "light1", "light2", "light3",
    "heavy", "special",
    "dodge", "hit", "jump",
    "portrait",
    "skill_icon_1", "skill_icon_2",
]

CHARACTERS = {
    "huikong": "Huikong",
    "tangtang": "Tangtang",
    "kiguemaru": "Kiguemaru",
}


def import_sprites(content_path: Path, dry_run: bool = False):
    """Import all sprite frames to UE5 Content directory."""

    manifest = []
    total_files = 0

    for src_char_dir, ue_char_name in CHARACTERS.items():
        src_dir = OUTPUT_DIR / src_char_dir
        if not src_dir.exists():
            print(f"  ⚠️  Source dir not found: {src_dir}")
            continue

        # Find all PNG files for this character
        frame_files = sorted(src_dir.glob("char_*.png"))
        if not frame_files:
            print(f"  ⚠️  No frames found for {src_char_dir}")
            continue

        # Group by animation type
        anim_groups = {}
        for f in frame_files:
            m = re.match(r'char_\w+_(\w+(?:_\d+)?)_(\d+)\.png', f.name)
            if m:
                anim = m.group(1)
                anim_groups.setdefault(anim, []).append(f)

        print(f"\n📦 {ue_char_name}: {len(frame_files)} frames, {len(anim_groups)} animations")

        for anim_type, files in sorted(anim_groups.items()):
            # UE5 Content path: Content/Characters/{Name}/{AnimType}/
            ue_dir = content_path / "Characters" / ue_char_name / anim_type.capitalize()
            ue_dir.mkdir(parents=True, exist_ok=True)

            copied = 0
            for src_file in files:
                dst_file = ue_dir / src_file.name
                if not dry_run:
                    shutil.copy2(src_file, dst_file)
                copied += 1
                total_files += 1

                manifest.append({
                    "character": ue_char_name,
                    "animation": anim_type,
                    "source": str(src_file),
                    "destination": str(dst_file),
                    "size_kb": src_file.stat().st_size // 1024,
                })

            print(f"    {anim_type}: {copied} frames → {ue_dir.relative_to(content_path)}")

    # Write manifest
    manifest_path = content_path / "import_manifest.json"
    if not dry_run:
        import json
        with open(manifest_path, 'w', encoding='utf-8') as f:
            json.dump(manifest, f, indent=2, ensure_ascii=False)
        print(f"\n✅ Manifest written: {manifest_path}")

    print(f"\n{'='*50}")
    print(f"Total: {total_files} frames imported")
    if dry_run:
        print("(DRY RUN — no files copied)")
    else:
        print(f"Destination: {content_path}")


def generate_python_import_script(content_path: Path):
    """Generate a UE5 Python API script for automated import."""

    script = f'''#!/usr/bin/env python3
"""
UE5 Python API import script — auto-generated by import_sprites_to_ue5.py
Run this inside UE5 Editor: Edit > Python > Execute Script
"""
import unreal

CONTENT_PATH = "{content_path.relative_to(PROJECT_ROOT)}"

# Import tasks for each character/animation
IMPORT_TASKS = [
'''

    for src_char_dir, ue_char_name in CHARACTERS.items():
        src_dir = OUTPUT_DIR / src_char_dir
        if not src_dir.exists():
            continue
        for f in sorted(src_dir.glob("char_*.png")):
            m = re.match(r'char_\w+_(\w+(?:_\d+)?)_(\d+)\.png', f.name)
            if m:
                anim = m.group(1)
                rel = f.relative_to(content_path)
                script += f'    ("{rel}", "Characters/{ue_char_name}/{anim.capitalize()}"),\n'

    script += ''']

def run_import():
    """Execute import tasks using UE5 Python API."""
    for src_file, dest_dir in IMPORT_TASKS:
        full_src = str(Path(unreal.Paths.project_dir()) / src_file)
        full_dest = str(Path(unreal.Paths.project_dir()) / CONTENT_PATH / dest_dir)

        task = unreal.AssetImportTask()
        task.filename = full_src
        task.destination_path = f"/Game/{dest_dir}"
        task.replace_existing = True
        task.automated = True

        unreal.AssetToolsHelpers.get_asset_tools().import_asset_tasks([task])
        print(f"  Imported: {src_file} -> /Game/{dest_dir}")

if __name__ == "__main__":
    run_import()
'''

    script_path = content_path / "auto_import_sprites.py"
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script)
    print(f"✅ UE5 Python import script: {script_path}")


def main():
    parser = argparse.ArgumentParser(description="Import sprite assets to UE5 Content/")
    parser.add_argument("--content-path", type=Path, default=DEFAULT_CONTENT_PATH,
                        help=f"UE5 Content directory (default: {DEFAULT_CONTENT_PATH})")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be imported without copying")
    parser.add_argument("--generate-ue-script", action="store_true",
                        help="Generate UE5 Python API import script")
    args = parser.parse_args()

    print(f" 格斗萌主 — Sprite Importer")
    print(f"   Source: {OUTPUT_DIR}")
    print(f"   Destination: {args.content_path}")
    print(f"   Dry run: {args.dry_run}")

    import_sprites(args.content_path, dry_run=args.dry_run)

    if args.generate_ue_script:
        generate_python_import_script(args.content_path)


if __name__ == "__main__":
    main()
